---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1
    # prefix for naming
    prefix: staging
    # availability zones
    az0: us-east-1a
    az1: us-east-1b

  tasks:
    - name: create vpc with multi-az subnets
      local_action:
        module: ec2_vpc
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
        resource_tags: '{"Name":"{{ prefix }}_vpc"}'
        subnets:
          - cidr: 10.0.0.0/24
            az: "{{ az0 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_public_0"}'
          - cidr: 10.0.1.0/24
            az: "{{ az0 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_private_0"}'
          - cidr: 10.0.2.0/24
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_public_1"}'
          - cidr: 10.0.3.0/24
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_private_1"}'
        internet_gateway: yes
        route_tables:
          - subnets:
            - 10.0.0.0/24
            - 10.0.2.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        wait: yes