---
- hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    #your region
    region: us-east-1
    #prefix for naming
    prefix: staging
  
  tasks:
    - name: get vpc information
      command: "aws ec2 describe-vpcs --filters Name=tag:Name,Values={{ prefix }}_vpc" 
      register: vpc_info
      changed_when: False

    - name: set vpc json information into variable
      set_fact: 
        vpc_info_json: "{{ vpc_info.stdout | from_json }}"
      changed_when: False

    - name: setup aws cli varables 
      set_fact: 
        VpcId: "{{ vpc_info_json.Vpcs[0].VpcId }}"
      when: vpc_info_json.Vpcs[0].VpcId is defined
  
    - name: get current ip for AWS
      uri: url=http://checkip.amazonaws.com/ 
           return_content=yes 
           method=GET 
      register: checkip

    - name: create security group for jump box instance
      local_action:
        module: ec2_group
        region: "{{ region }}"
        vpc_id: "{{ VpcId }}"
        #your security group name
        name: "{{ prefix }}_sg_jumpbox"
        description: security group for jump box
        rules:
          # allow ssh access from your ip address
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ checkip.content | regex_replace('\n', '/32') }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0