---
- hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    region: us-east-1
  
  tasks:
    - name: create mysql parameter group
      local_action:
        module: rds_param_group
        name: mysqlpg1
        state: present
        region: "{{ region }}"
        description: MySQL Parameter Group 1
        engine: mysql5.6
        params:
          innodb_lock_wait_timeout: 3600
          character_set_database: utf8